### PR TITLE
- Update activerecord to 7.0.4 to support rails 7.0.4

### PR DESCRIPTION
**Pull request by Bhalani**
### Issue # (if available)
It's not working for my Rails 7.0.4 application

### Description of changes
Update gem `activerecord` to `7.0.4`
And make sure it works with rails latest version.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Bhalani** [comment]
@reidmorrison Please review it, my project is in Rails 7.0.4 and I'm not able to access `attr_encrypted` because of current version support is 7.0.0.
I don't see any issue down the road by updating Activerecord 7.0.4.
Please add some feedback or approve it so other user can also take benefit of this update.

**Comment by reidmorrison** [comment]
Rails 7 has its own `attractive_encrypted` method that conflicts with the one used by Symmetric Encryption, as a result this method is no longer supported as of Rails 7. The new approach is documented here: https://encryption.rocketjob.io/frameworks.html

**Comment by reidmorrison** [comment]
This is the pull request that describes the problem: https://github.com/reidmorrison/symmetric-encryption/pull/156

**Comment by reidmorrison** [comment]
attr_encrypted is no longer available when using Rails 7. The newer approach is documented here: https://encryption.rocketjob.io/frameworks.html.

**Pull request closed without merging**
